version: '3.9'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app/frontend
      - ../.env:/app/.env 
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

